import type { AppState } from "@/types";

export function makeInitialState(): AppState {
  return {
    onboarded: false,
    profile: {
      displayName: "Pond Keeper",
      mascot: "turtley",
      mascotName: "Turtley",
      themeId: "pond_mint",
      timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC",
      isPremium: false,
      createdAt: new Date().toISOString(),
    },
    wallet: { balance: 0, lifetimeEarned: 0, lifetimeSpent: 0 },
    ledger: [],
    entries: {},
    shields: [],
    factsRead: {},
    inventory: {},
    achievements: {},
    notifications: {
      dailyReminderEnabled: true,
      reminderTime: "19:00",
      streakRiskEnabled: true,
      factOfDayEnabled: false,
      soundEnabled: false,
      hapticsEnabled: true,
      pushEnabled: false,
    },
    prefs: {
      calmMode: false,
      reduceMotion: false,
      reduceTransparency: false,
      highContrast: false,
      largeText: false,
      gentleStreak: false,
      focusMode: false,
      surpriseBonuses: true,
      breakNudges: true,
    },
    // explicit so reset() (a shallow merge) clears any prior values
    factOfDayClaimedOn: undefined,
    autoShieldCheckedOn: undefined,
    lastReminderOn: undefined,
    loginBonusClaimedOn: undefined,
    game: undefined,
    mantra: undefined,
    gamesWon: 0,
    mantrasFocused: 0,
    quest: undefined,
    collection: {},
    lastBoosterOn: undefined,
    perfectDays: 0,
    lastPerfectDayOn: undefined,
    hatch: { care: 0, collection: {}, total: 0 },
    cloud: { autoBackup: false },
  };
}
