// Builds an IDEMPOTENT supabase/schema.sql from the migrations, so it can be run
// safely on a fresh OR partially-applied project (run: node scripts/gen-schema.mjs).
import { readFileSync, writeFileSync } from "node:fs";

const files = ["0001_init", "0002_seed_catalog", "0003_user_state", "0004_push", "0005_server_economy", "0006_fact_cards_seed"];
const dir = new URL("../supabase/migrations/", import.meta.url);

let body = files
  .map((f) => `-- ====================== ${f}.sql ======================\n` + readFileSync(new URL(`${f}.sql`, dir), "utf8"))
  .join("\n\n");

// 1) types — tolerate "already exists" (handles aligned whitespace before `as`)
body = body.replace(/create type (\w+)\s+as enum\s*\(([\s\S]*?)\);/g,
  (_m, name, vals) => `do $$ begin\n  create type ${name} as enum (${vals});\nexception when duplicate_object then null;\nend $$;`);

// 1b) on an already-migrated DB the enum exists, so the "create type" above is
// skipped and newer reasons would be missing — backfill them explicitly.
const LEDGER_REASONS = [
  "upload","streak_bonus","milestone","note_bonus","meta_bonus","challenge","fact_read",
  "fact_of_day","repair","ai_rescue","shield_buy","shop_purchase","onboarding_gift","minigame",
  "mantra","task","daily_login","lucky_upload","lucky_game","lucky_mantra","booster",
  "booster_open","booster_reward","refund","admin",
];
const ensureReasons = "-- backfill any ledger reasons missing from a previously-created enum\n" +
  LEDGER_REASONS.map((r) => `alter type ledger_reason_t add value if not exists '${r}';`).join("\n") + "\n\n";
body = body.replace("create table app_user", ensureReasons + "create table app_user");

// 2) tables — add IF NOT EXISTS where missing
body = body.replace(/create table (?!if not exists)/g, "create table if not exists ");

// 3) policies — drop-then-create (covers standalone + the format() loop via %1$I)
body = body.replace(/create policy ("[^"]+") on (\S+)/g, "drop policy if exists $1 on $2;\ncreate policy $1 on $2");

// 4) triggers — drop-then-create (handles multi-line defs)
body = body.replace(/create trigger (\w+)([\s\S]*?)\s+on\s+([\w.]+)\s+for\s+each\s+row/g,
  (_m, name, mid, tbl) => `drop trigger if exists ${name} on ${tbl};\ncreate trigger ${name}${mid} on ${tbl} for each row`);

const storage = `-- ====================== storage: turtle photo bucket + policies ======================
insert into storage.buckets (id, name, public) values ('turtles','turtles', true)
  on conflict (id) do nothing;
drop policy if exists "own turtle uploads" on storage.objects;
create policy "own turtle uploads" on storage.objects for insert to authenticated
  with check (bucket_id = 'turtles' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "own turtle updates" on storage.objects;
create policy "own turtle updates" on storage.objects for update to authenticated
  using (bucket_id = 'turtles' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "own turtle deletes" on storage.objects;
create policy "own turtle deletes" on storage.objects for delete to authenticated
  using (bucket_id = 'turtles' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "public turtle reads" on storage.objects;
create policy "public turtle reads" on storage.objects for select using (bucket_id = 'turtles');
`;

const header = `-- ============================================================================
-- TurtWatch — COMPLETE backend in ONE idempotent file.
-- Safe to run on a fresh OR already-partially-migrated Supabase project (SQL
-- editor). Re-runnable. Includes core schema, server-authoritative economy,
-- the 336-card seed, push tables, and the storage bucket + policies.
-- AUTO-GENERATED by scripts/gen-schema.mjs — do not edit by hand.
-- ============================================================================

`;

writeFileSync(new URL("../supabase/schema.sql", import.meta.url), header + body + "\n\n" + storage);
console.log("Wrote idempotent supabase/schema.sql");
